了解しました。`tools/hypothesis_generator.py` の文字列リテラルで改行やバッククォートを含む箇所が不適切に扱われ、Python の未終了文字列エラーが出ています。以下は修正済みの完全な `hypothesis_generator.py`（単体で保存して実行可能）です。既存のファイルをこれで上書きしてください。

保存先: omega_theory_pkg/tools/hypothesis_generator.py

```python
#!/usr/bin/env python3
# tools/hypothesis_generator.py
# Generate simple hypotheses from extracted PDF text and optional seed.

import argparse
import os
import random
import re
import datetime

R = random.Random()
OP_POOL = ['nabla', 'Delta', 'INT', 'SUM', 'zeta', 'Gamma', 'partial']

def load_text(path):
    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        return f.read()

def extract_keywords(text, k=40):
    words = re.findall(r"\w+", text)
    freq = {}
    for w in words:
        if len(w) < 3:
            continue
        freq[w] = freq.get(w, 0) + 1
    items = sorted(freq.items(), key=lambda x: -x[1])
    return [w for w, _ in items[:k]]

def propose_hypotheses(pdf_text, seed_theory, count=3):
    kws = extract_keywords(pdf_text)
    hyps = []
    for i in range(count):
        ks = R.sample(kws, k=min(len(kws), 1 + R.randint(0, 2))) if kws else ['x']
        op = R.choice(OP_POOL)
        coef = str(R.randint(1, 9))
        seed_part = ''
        if seed_theory and R.random() < 0.6:
            seed_part = ' // seed: ' + (seed_theory[:200])
        formula = '{} {} {} = 0'.format(coef, op, '*'.join(ks))
        hyps.append({
            'id': i + 1,
            'formula': formula,
            'seed': seed_part,
            'remark': 'autogenerated hypothesis #{}'.format(i + 1)
        })
    return hyps

def save_hypotheses(hyps, outdir, basename='hypothesis'):
    os.makedirs(outdir, exist_ok=True)
    for h in hyps:
        ts = datetime.datetime.utcnow().isoformat()
        fname = os.path.join(outdir, '{}_{:03d}.md'.format(basename, h['id']))
        # Use triple-quoted string segments and explicit writes to avoid literal issues
        header = "# Hypothesis {}\n# {}\n\n".format(h['id'], ts)
        formula_section = "Formula:\n```\n{}\n```\n\n".format(h['formula'])
        seed_section = ""
        if h['seed']:
            seed_section = "Seed snippet:\n```\n{}\n```\n\n".format(h['seed'])
        remark_section = "Remark: {}\n".format(h.get('remark', 'autogenerated'))
        with open(fname, 'w', encoding='utf-8') as f:
            f.write(header)
            f.write(formula_section)
            if seed_section:
                f.write(seed_section)
            f.write(remark_section)
    return len(hyps)

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--pdf_text', required=True)
    p.add_argument('--seed', default='')
    p.add_argument('--count', type=int, default=3)
    p.add_argument('--outdir', default='generated')
    args = p.parse_args()

    text = load_text(args.pdf_text)
    hyps = propose_hypotheses(text, args.seed, args.count)
    n = save_hypotheses(hyps, args.outdir)
    print('Saved', n, 'hypotheses to', args.outdir)

if __name__ == '__main__':
    main()
```

ポイント
- 各ファイル書き出しで triple-quoted 構文や連結ではなく、フォーマット済み文字列を個別に書き出すようにして、未終了文字列の発生源を排除しました。
- バッククォートや改行は文字列内で安全に扱っています。

これで該当の SyntaxError は解消されるはずです。上書き後に再実行して、もし別の行で同様のエラーが出る場合は、そのエラーメッセージ（行番号と該当行）を教えてください。
