plugins {
    id 'com.android.application'
}

android {
    namespace 'io.bada.omega.iqtelomere'
    compileSdk 34

    defaultConfig {
        applicationId "io.bada.omega.iqtelomere"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
