#!/usr/bin/env python3
"""Assemble the downloadable Windows keybinding package.

Generates the .reg files from the Bada config (apps/mayu_pack.bada), copies the
portable mayu executable next to the hand-written installer scripts / README in
download/, and zips the lot into dist/madotsukai_windows.zip.

    python3 tools/build_download.py

The download/ directory is committed so every file is individually downloadable
from the repository; the .zip is the one-click bundle.
"""

import os
import sys
import shutil
import subprocess
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # bada_lang/
DIST = os.path.join(ROOT, "dist")
DOWNLOAD = os.path.join(ROOT, "download")
BADA = os.path.join(ROOT, "bada.py")

# generated by apps/mayu_pack.bada
GENERATED = ["keybindings.mayu", "emacs.mayu", "vim.mayu", "apps.mayu",
             "windows11.reg", "windows10.reg",
             "scancode-capslock-ctrl.reg", "uninstall.reg"]
# hand-written, already in download/
STATIC = ["README.md", "install.bat", "install.ps1", "uninstall.bat",
          "mayu_agent.py", "run_mayu.bat", "run_mayu_vim.bat"]


def main():
    os.makedirs(DOWNLOAD, exist_ok=True)

    # 1. generate the .reg files + editable config into download/
    print("generating .reg files from apps/mayu_pack.bada ...")
    r = subprocess.run([sys.executable, BADA, "run",
                        os.path.join(ROOT, "apps", "mayu_pack.bada")],
                       cwd=DOWNLOAD, capture_output=True, text=True, timeout=120)
    sys.stdout.write(r.stdout)
    if r.returncode != 0:
        sys.stderr.write(r.stderr)
        sys.exit("mayu_pack failed")

    # 2. make sure the portable executable is built, then copy it in
    mayu_pyz = os.path.join(DIST, "mayu.pyz")
    if not os.path.isfile(mayu_pyz):
        subprocess.run([sys.executable, os.path.join(ROOT, "tools", "build_exe.py")],
                       check=True)
    shutil.copy(mayu_pyz, os.path.join(DOWNLOAD, "mayu.pyz"))
    print("copied mayu.pyz")

    # 3. verify the hand-written files are present
    for nm in STATIC:
        if not os.path.isfile(os.path.join(DOWNLOAD, nm)):
            sys.exit("missing static file: download/" + nm)

    # 4. zip everything
    os.makedirs(DIST, exist_ok=True)
    out_zip = os.path.join(DIST, "madotsukai_windows.zip")
    if os.path.exists(out_zip):
        os.remove(out_zip)
    members = STATIC + GENERATED + ["mayu.pyz"]
    # mayu.exe is produced by the Windows CI job and merged into the zip there;
    # include it locally too if a build happens to be present.
    if os.path.isfile(os.path.join(DOWNLOAD, "mayu.exe")):
        members.append("mayu.exe")
    with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as z:
        for nm in members:
            full = os.path.join(DOWNLOAD, nm)
            if os.path.isfile(full):
                z.write(full, os.path.join("madotsukai", nm))

    print("\nbuilt: dist/madotsukai_windows.zip  (%d files, %d bytes)"
          % (len(members), os.path.getsize(out_zip)))
    print("       download/  (committed - each file individually downloadable)")


if __name__ == "__main__":
    main()
