---
mountOptions:
    default: defaults,noatime
    btrfs:   defaults,noatime,compress=zstd
efiMountOptions: umask=0077
ssdExtraMountOptions:
    ext4:  discard
    btrfs: discard,ssd
crypttabOptions: luks
