---
efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize:  300M
userSwapChoices:
    - none
    - small
    - suspend
drawNestedPartitions:   false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
initialPartitioningChoice: erase
initialSwapChoice:      none
defaultFileSystemType:  "ext4"
availableFileSystemTypes: [ "ext4", "btrfs", "xfs" ]
