---
defaultGroups:
    - adm
    - cdrom
    - sudo
    - dip
    - plugdev
    - lpadmin
    - netdev
autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    sudo
setRootPassword:  false
doReusePassword:  true
availableShells:  /bin/bash, /bin/zsh
avatarFilePath:   ""
userShell:        /bin/bash

passwordRequirements:
    minLength: 1
    maxLength: -1

allowWeakPasswords:        true
allowWeakPasswordsDefault: true
