# frozen_string_literal: true

require "minitest/autorun"
require_relative "../lib/bada"

class TestCreditGuard < Minitest::Test
  def test_bb84_distributes_a_256bit_key_with_zero_qber
    r = Bada::CreditGuard.bb84(bits: 256, seed: 12345)
    assert_equal 32, r[:key].bytesize          # 256-bit whitened key
    assert_operator r[:sifted], :>=, 256        # enough sifted bits
    assert_in_delta 0.0, r[:qber], 1e-12        # no eavesdropper -> QBER 0
    assert_operator r[:sent], :>, r[:sifted]    # sifting discards ~half
  end

  def test_bb84_is_reproducible_for_a_fixed_seed
    a = Bada::CreditGuard.bb84(bits: 256, seed: 7)[:key]
    b = Bada::CreditGuard.bb84(bits: 256, seed: 7)[:key]
    assert_equal a, b
  end

  def test_seal_verifies_and_detects_tampering
    content = "generated by NoemaKey / 未知事前予知エンジン"
    seal = Bada::CreditGuard.seal(content)
    assert Bada::CreditGuard.verify(content, seal)
    refute Bada::CreditGuard.verify(content + "x", seal)      # tampered content
    refute Bada::CreditGuard.verify(content, seal.succ)       # tampered seal
  end

  def test_stamp_embeds_a_verifiable_credit_footer
    stamped = Bada::CreditGuard.stamp("hello")
    assert_includes stamped, "量子暗号クレジット保護"
    assert_includes stamped, Bada::CreditGuard.fingerprint
    assert_includes stamped, "Masaaki Yamaguchi"
  end

  def test_precog_output_is_credit_sealed
    p = Bada::Precog.new(seed: 42)
    p.learn("ゼータ関数とベータ関数の関係。", source: "t")
    out = p.ask("ゼータ関数")
    assert_includes out, "量子暗号クレジット保護"
    assert_includes out, Bada::CreditGuard.fingerprint
  end
end
