#!/usr/bin/env python3
"""Render contact_machine.obj to a PNG preview (matplotlib, flat-shaded)."""
import sys
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

COLORS = {"gimbal": "#c8a44a", "pod": "#e8e8f0", "tower": "#5a6270", "gantry": "#5a6270",
          "drop": "#8090a0", "jones_coil_3_1": "#4a80d0", "jones_coil_5_1": "#9060d0",
          "jones_coil_4_1": "#40b8c0", "door": "#ff5050", "resonance": "#ff9040"}


def color(group):
    for k, c in COLORS.items():
        if group.startswith(k):
            return c
    return "#888888"


def load(path):
    verts, faces, group = [], [], "default"
    for line in open(path):
        if line.startswith("v "):
            verts.append([float(t) for t in line.split()[1:4]])
        elif line.startswith("g "):
            group = line.split(None, 1)[1].strip()
        elif line.startswith("f "):
            faces.append(([int(t.split("/")[0]) - 1 for t in line.split()[1:]], group))
    return np.array(verts), faces


def main(obj, png):
    V, F = load(obj)
    light = np.array([0.4, -0.5, 0.75]); light /= np.linalg.norm(light)
    fig = plt.figure(figsize=(12, 6), facecolor="#04060a")
    for k, (elev, azim, title) in enumerate([(22, -60, "perspective"), (90, -90, "top (xy)")]):
        ax = fig.add_subplot(1, 2, k + 1, projection="3d", facecolor="#04060a")
        polys, cols = [], []
        for idx, g in F:
            P = V[idx]
            n = np.cross(P[1] - P[0], P[2] - P[0]); nn = np.linalg.norm(n)
            shade = 0.35 + 0.65 * abs(n @ light) / nn if nn > 0 else 0.6
            c = np.array(matplotlib.colors.to_rgb(color(g))) * shade
            polys.append(P); cols.append(np.clip(c, 0, 1))
        ax.add_collection3d(Poly3DCollection(polys, facecolors=cols, edgecolors="none"))
        r = np.abs(V).max() * 0.75
        ax.set_xlim(-r, r); ax.set_ylim(-r, r); ax.set_zlim(-r * 0.6, r * 1.4)
        ax.view_init(elev=elev, azim=azim); ax.set_axis_off()
        ax.set_title(title, color="#c8a44a")
    fig.suptitle("Contact Transporter — generated by Bada", color="#e8e8f0")
    fig.savefig(png, dpi=110, facecolor=fig.get_facecolor(), bbox_inches="tight")
    print("wrote", png)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
