# Calamares 設定 — Bada VM Pro OS を実ディスクへインストール
---
modules-search: [ local, /usr/lib/x86_64-linux-gnu/calamares/modules ]

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader
  - grubcfg
  - packages
  - umount
- show:
  - finished

branding: badaos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
