"""Contact Machine blueprint — the 3-D design of the transport Machine from
the film "Contact", generated by a Bada program (apps/contact/)."""

from . import bridge
from .app import ContactApp

__all__ = ["bridge", "ContactApp"]
