"""ContactApp — runs the Bada blueprint generator and writes the 3-D
blueprint as Wavefront OBJ, a text report, and a self-contained HTML viewer."""

from __future__ import annotations

import html
import json
import os

from . import bridge

PART_COLORS = {
    "ring_precession": "#d97706",
    "ring_nutation": "#2563eb",
    "ring_spin": "#16a34a",
    "pod": "#db2777",
    "gantry": "#6b7280",
}


class ContactApp:
    def __init__(self):
        self.report = ""
        self.obj = ""
        self.parts: list[dict] = []

    def generate(self) -> "ContactApp":
        self.report, self.obj = bridge.split_output(bridge.run_app())
        self.parts = bridge.parse_obj(self.obj)
        return self

    def html(self) -> str:
        data = json.dumps([{"name": p["name"], "color": PART_COLORS.get(p["name"], "#888"),
                            "v": p["vertices"], "e": p["edges"]} for p in self.parts])
        legend = "".join(
            f'<span><i style="background:{PART_COLORS.get(p["name"], "#888")}"></i>'
            f'{html.escape(p["name"])}</span>' for p in self.parts)
        return _HTML.replace("__DATA__", data).replace(
            "__REPORT__", html.escape(self.report)).replace("__LEGEND__", legend)

    def save(self, outdir: str) -> dict:
        os.makedirs(outdir, exist_ok=True)
        paths = {
            "obj": os.path.join(outdir, "contact_machine.obj"),
            "report": os.path.join(outdir, "contact_report.txt"),
            "html": os.path.join(outdir, "contact_blueprint.html"),
        }
        with open(paths["obj"], "w") as f:
            f.write(self.obj)
        with open(paths["report"], "w") as f:
            f.write(self.report)
        with open(paths["html"], "w") as f:
            f.write(self.html())
        return paths


_HTML = """<!doctype html>
<html lang="ja"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Contact Machine Blueprint</title>
<style>
:root{--bg:#f7f7f5;--fg:#1c1c1c;--muted:#666;--panel:#fff;--line:#ddd}
@media (prefers-color-scheme:dark){:root{--bg:#141414;--fg:#e8e8e8;--muted:#999;--panel:#1d1d1d;--line:#333}}
body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.5 system-ui,sans-serif}
main{max-width:1000px;margin:0 auto;padding:16px}
h1{font-size:20px;margin:0 0 4px}
p.sub{color:var(--muted);margin:0 0 12px}
canvas{width:100%;aspect-ratio:4/3;background:var(--panel);border:1px solid var(--line);border-radius:8px;touch-action:none;cursor:grab}
.legend{display:flex;flex-wrap:wrap;gap:12px;margin:8px 0}
.legend i{display:inline-block;width:12px;height:12px;border-radius:2px;margin-right:6px;vertical-align:-1px}
pre{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:12px;overflow-x:auto;font-size:12px}
</style></head><body><main>
<h1>Contact Machine — 3D Blueprint</h1>
<p class="sub">Generated by <code>apps/contact/contact_app.bada</code> on the Bada VM. Drag to rotate. Design fiction: the numbers are exact, the physics reading is hypothetical.</p>
<canvas id="c" width="1000" height="750"></canvas>
<div class="legend">__LEGEND__</div>
<pre>__REPORT__</pre>
</main>
<script>
const parts = __DATA__;
const cv = document.getElementById('c'), ctx = cv.getContext('2d');
let yaw = 0.6, pitch = 0.35, drag = null;
let zc = 0, span = 1;
(function(){let lo=1e9,hi=-1e9,r=0;for(const p of parts)for(const v of p.v){lo=Math.min(lo,v[2]);hi=Math.max(hi,v[2]);r=Math.max(r,Math.hypot(v[0],v[1]));}zc=(lo+hi)/2;span=Math.max(hi-lo,2*r);})();
function proj(v){
  const x=v[0], y=v[1], z=v[2]-zc;
  const cy=Math.cos(yaw), sy=Math.sin(yaw), cp=Math.cos(pitch), sp=Math.sin(pitch);
  const x1=cy*x-sy*y, y1=sy*x+cy*y;
  const y2=cp*y1-sp*z, z2=sp*y1+cp*z;
  const s=cv.height*0.85/span, d=3*span, f=d/(d+y2);
  return [cv.width/2+x1*s*f, cv.height/2-z2*s*f];
}
function draw(){
  ctx.clearRect(0,0,cv.width,cv.height);
  ctx.lineWidth=1.5;
  for(const p of parts){
    ctx.strokeStyle=p.color; ctx.beginPath();
    for(const [a,b] of p.e){const A=proj(p.v[a]),B=proj(p.v[b]);ctx.moveTo(A[0],A[1]);ctx.lineTo(B[0],B[1]);}
    ctx.stroke();
  }
}
cv.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];cv.setPointerCapture(e.pointerId);});
cv.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*0.01;pitch=Math.max(-1.5,Math.min(1.5,pitch+(e.clientY-drag[1])*0.01));drag=[e.clientX,e.clientY];draw();});
cv.addEventListener('pointerup',()=>{drag=null;});
draw();
</script></body></html>
"""
