#!/usr/bin/env python3
import sys,json,random,re
def load_subterms(path):
    L=[json.loads(l) for l in open(path,'r',encoding='utf-8') if l.strip()]
    pool=[]
    for e in L:
        for s in e.get('subterms',[]): pool.append({'source_id':e.get('id'),'text':s})
    return pool
def transform_term(t):
    # apply small transforms: scale, offset, wrap in function
    ops=['','*k','+k','-k','**2','**1.5','(1/({t}))']
    choice=random.choice(ops)
    k=round(random.uniform(0.5,3.0),3)
    if choice=='(1/({t}))': return (choice.format(t=t), f'inverted {t}')
    return (f'({t}){choice.replace("k",str(k))}', f'applied {choice.replace("k","k")}' )
def combine(a,b):
    patterns=['{a} + {b}','{a} - {b}','{a}*{b}','{a}/{b}','{a}*exp(-{b})','Gamma({a} + {b})']
    p=random.choice(patterns)
    return p.format(a=a,b=b)
def explain(a_expl,b_expl,rule):
    return f'Generated by combining [{a_expl}] and [{b_expl}] using rule "{rule}"'
def main():
    if len(sys.argv)<4:
        print('Usage: equation_generator.py decomposed.jsonl out.jsonl [n]')
        return 2
    n=int(sys.argv[3]) if len(sys.argv)>3 else 8
    pool=load_subterms(sys.argv[1])
    gens=[]
    if not pool:
        pool=[{'source_id':'S','text':'x'},{'source_id':'S','text':'y'},{'source_id':'S','text':'t'}]
    for i in range(n):
        a=random.choice(pool); b=random.choice(pool)
        at, a_expl = transform_term(a['text'])
        bt, b_expl = transform_term(b['text'])
        expr = combine(at, bt)
        expl = f'From parts: {a["text"]} (src:{a["source_id"]}) and {b["text"]} (src:{b["source_id"]}). Transforms: {a_expl}, {b_expl}. Combined with pattern.'
        gens.append({'id':f'G{i}','raw':expr,'explanation':expl,'parts':[a,b]})
    open(sys.argv[2],'w',encoding='utf-8').write('\n'.join(json.dumps(g,ensure_ascii=False) for g in gens))
    print('Generated',len(gens),'equations with explanations')
if __name__=='__main__': sys.exit(main())
