DEFAULT_MAPPINGS = {
    "ctrl+f": "right",
    "ctrl+b": "left",
    "ctrl+n": "down",
    "ctrl+p": "up",
    "ctrl+a": "home",
    "ctrl+e": "end",
    "alt+f": "ctrl+right",
    "alt+b": "ctrl+left",
    "ctrl+d": "delete",
    "backspace": "backspace",
    "ctrl+k": "shift+end, ctrl+x",
    "ctrl+y": "ctrl+v",
    "ctrl+_": "ctrl+z",
    "ctrl+/": "ctrl+z",
    "ctrl+s": "ctrl+f",
    "ctrl+r": "ctrl+shift+f",
    "ctrl+v": "pagedown",
    "alt+v": "pageup",
    "ctrl+g": "",
}
