# frozen_string_literal: true

require "json"
require_relative "../manifold"
require_relative "../thurston"
require_relative "../millennium"

module Bada
  module Penrose
    # AppFactory — an application that BUILDS applications (アプリを作るアプリ).
    #
    # Input: a NETWORK of equations (方程式同士のネットワーク) — a list of steps
    # where each step is an equation whose value may feed later steps (dataflow).
    # This is exactly the chain the Penrose studio produces when you save results
    # (R1, R2, …) and combine them with 加減乗除.
    #
    # AppFactory then:
    #   1. semantically annotates each equation with the Bada "未知事前予知エンジン"
    #      (InfoEngine's manifold invariant Ξ, Thurston–Perelman geometry, and the
    #      dominant Clay-Millennium theory) — 意味付け;
    #   2. generates runnable SOURCE CODE (Ruby) for the whole network; and
    #   3. generates a self-contained, downloadable HTML APPLICATION that runs the
    #      network and shows its meaning — i.e. the generated application itself
    #      is a downloadable artifact.
    module AppFactory
      module_function

      # network: { name:, steps: [ {name:, equation:, inputs:[], value:, op:} ] }
      #   * value present  -> a source equation (leaf) of the network
      #   * op + inputs     -> a combining equation (＋ − × ÷) over prior steps
      def generate(network)
        name = network[:name] || "GeneratedApp"
        steps = network[:steps] || []
        meaning = steps.map { |s| annotate(s) }
        {
          name: name,
          meaning: meaning,
          overall: overall_meaning(name, steps),
          source: ruby_source(name, steps, meaning),
          html: app_html(name, steps, meaning)
        }
      end

      # ---- 未知事前予知エンジンによる意味付け (semantic annotation) -----
      def annotate(step)
        text = step[:equation].to_s
        inv = Manifold.invariant(text)
        place = Thurston.place_entropy(text)
        mil = Millennium.decompose_theory(text)
        {
          name: step[:name],
          equation: text,
          entropy: inv[:entropy],
          invariant: inv[:invariant],                 # Ξ
          geometry: place[:geometry],
          curvature: place[:curvature],
          perelman_f: place[:perelman_f],
          dominant: mil[:dominant],                   # 主たる理論
          theory: mil[:decomposition].first[:theory]
        }
      end

      def overall_meaning(name, steps)
        joined = steps.map { |s| s[:equation] }.join(" ; ")
        inv = Manifold.invariant(joined.empty? ? name : joined)
        mil = Millennium.decompose_theory(joined.empty? ? name : joined)
        place = Thurston.place_entropy(joined.empty? ? name : joined)
        {
          invariant: inv[:invariant],
          geometry: place[:geometry],
          dominant: mil[:dominant],
          origin: mil[:origin]
        }
      end

      # ---- generated Ruby source ---------------------------------------
      def ruby_source(name, steps, meaning)
        lines = []
        lines << "# frozen_string_literal: true"
        lines << "# Auto-generated by Bada::Penrose::AppFactory (アプリを作るアプリ)."
        lines << "# Application: #{name}"
        lines << "# 方程式ネットワーク: 各ステップは前段の出力を入力にとる (dataflow)."
        lines << "# 未知事前予知エンジンによる意味付けは各行の注釈に記す。"
        lines << ""
        lines << "STEPS = {}"
        lines << ""
        lines << "# elementwise ＋ − × ÷ with scalar broadcast (加減乗除)"
        lines << "def ew(a, b, op)"
        lines << "  if a.is_a?(Array) && b.is_a?(Array)"
        lines << "    a.each_index.map { |i| ew(a[i], b[i], op) }"
        lines << "  elsif a.is_a?(Array) then a.map { |x| ew(x, b, op) }"
        lines << "  elsif b.is_a?(Array) then b.map { |x| ew(a, x, op) }"
        lines << "  else case op"
        lines << "       when \"+\", \"＋\" then a + b"
        lines << "       when \"-\", \"−\" then a - b"
        lines << "       when \"*\", \"×\" then a * b"
        lines << "       when \"/\", \"÷\" then b.zero? ? Float::NAN : a.fdiv(b)"
        lines << "       end"
        lines << "  end"
        lines << "end"
        lines << ""
        steps.each_with_index do |s, i|
          m = meaning[i]
          note = "  # #{s[:equation]}  |  Ξ=#{format('%.4f', m[:invariant])}, " \
                 "幾何=#{m[:geometry]}, 主理論=#{m[:dominant]}"
          if s[:op] && s[:inputs]
            a, b = s[:inputs]
            bexpr = b && steps.any? { |x| x[:name] == b } ? "STEPS[#{b.inspect}]" : b.inspect
            lines << "STEPS[#{s[:name].inspect}] = ew(STEPS[#{a.inspect}], #{bexpr}, #{s[:op].inspect})"
            lines << note
          else
            lines << "STEPS[#{s[:name].inspect}] = #{s[:value].inspect}"
            lines << note
          end
        end
        lines << ""
        lines << "STEPS.each { |k, v| puts \"#{'#{k}'} = #{'#{v.inspect}'}\" }"
        lines.join("\n")
      end

      # ---- generated downloadable HTML application ---------------------
      def app_html(name, steps, meaning)
        rows = steps.each_with_index.map do |s, i|
          m = meaning[i]
          val = s[:value].nil? && s[:op] ? "(#{s[:inputs].join(" #{s[:op]} ")})" : JSON.generate(s[:value])
          <<~ROW
            <div class="node">
              <div class="hd"><b>#{s[:name]}</b> <code>#{escape(s[:equation])}</code></div>
              <div class="val">値: #{escape(val)}</div>
              <div class="mean">意味 (未知事前予知エンジン): Ξ=#{format('%.4f', m[:invariant])} ·
                幾何 #{escape(m[:geometry])}(曲率#{format('%.2f', m[:curvature])}) ·
                主理論 <b>#{escape(m[:dominant])}</b></div>
            </div>
          ROW
        end.join("\n")

        <<~HTML
          <!DOCTYPE html>
          <html lang="ja"><head><meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>#{escape(name)} — Bada 生成アプリ</title>
          <style>
            body{margin:0;font-family:-apple-system,"Segoe UI","Noto Sans JP",sans-serif;background:#0b0e14;color:#e6ecf3}
            header{padding:16px 20px;border-bottom:1px solid #26303f;background:#101622}
            h1{margin:0;font-size:18px;color:#c8a44a} .sub{color:#9fb0c3;font-size:12px;margin-top:4px}
            main{padding:16px;display:flex;flex-direction:column;gap:10px;max-width:860px}
            .node{background:#141a24;border:1px solid #26303f;border-radius:8px;padding:12px}
            .node .hd{font-size:14px} .node code{color:#40b8c0}
            .node .val{font-size:13px;color:#c8a44a;margin-top:4px;font-family:Consolas,monospace}
            .node .mean{font-size:12px;color:#9fb0c3;margin-top:6px}
            footer{padding:12px 20px;border-top:1px solid #26303f;color:#6c7a8d;font-size:11px}
          </style></head><body>
          <header><h1>#{escape(name)}</h1>
          <div class="sub">Bada「アプリを作るアプリ」が方程式ネットワークから生成した自己完結アプリ。</div></header>
          <main>#{rows}</main>
          <footer>© Bada — AppFactory 生成物 · 未知事前予知エンジンで意味付け</footer>
          </body></html>
        HTML
      end

      def escape(s)
        s.to_s.gsub("&", "&amp;").gsub("<", "&lt;").gsub(">", "&gt;")
      end
    end
  end
end
