# frozen_string_literal: true

require_relative "diagram"
require_relative "evaluator"

module Bada
  module Penrose
    # Generate runnable source code from a drawn Penrose diagram. This is the
    # "ソースコード生成" output: a self-contained Ruby program that rebuilds the
    # diagram via the DSL and computes the contraction.
    module CodeGenerator
      module_function

      def ruby(diagram, drawing: nil)
        r = diagram.resolve
        lines = []
        lines << "# Auto-generated by Bada::Penrose from a drawn diagram."
        lines << "#   #{drawing.gsub("\n", ' / ')}" if drawing
        lines << "#   einsum: #{diagram.einsum_string}"
        lines << "require \"bada/penrose/diagram\""
        lines << "require \"bada/penrose/evaluator\""
        lines << "include Bada::Penrose"
        lines << ""
        lines << "diagram = Diagram.build do"
        diagram.nodes.each do |name, node|
          val = node.value ? ", value: #{node.value.inspect}" : ""
          lines << "  tensor #{name.inspect}, legs: #{node.legs}#{val}"
        end
        diagram.wires.each do |w|
          lines << "  contract #{w.a.inspect}, #{w.b.inspect}"
        end
        diagram.frees.each do |f|
          lines << "  free #{f.slot.inspect}, #{f.label.inspect}"
        end
        diagram.decorators.each do |d|
          case d.type
          when :nabla then lines << "  nabla #{Array(d.target).first.inspect}, #{d.label.inspect}"
          when :partial then lines << "  partial #{Array(d.target).first.inspect}, #{d.label.inspect}"
          when :integral then lines << "  integral #{d.label.inspect}"
          when :sym then lines << "  symmetrize #{Array(d.target).map(&:inspect).join(', ')}"
          when :antisym then lines << "  antisymmetrize #{Array(d.target).map(&:inspect).join(', ')}"
          end
        end
        lines << "end"
        lines << ""
        lines << "result = Evaluator.evaluate(diagram)"
        lines << "puts result[:einsum]"
        lines << "p result[:result]"
        lines.join("\n")
      end

      # A dependency-free pure-function version (no Bada require) that performs
      # the same Einstein summation directly — useful as an exportable kernel.
      def standalone_ruby(diagram)
        r = diagram.resolve
        out = r[:output]
        node_specs = diagram.nodes.map do |name, node|
          "  # #{name}_{#{r[:assignment][name].join(' ')}}#{node.value ? " = #{node.value.inspect}" : ''}"
        end
        <<~RUBY
          # Standalone Einstein summation for: #{diagram.einsum_string}
          # tensors are nested arrays; index names per tensor below:
          #{node_specs.join("\n")}
          def einsum(tensors, dims, output)
            names = dims.keys
            out_shape = output.map { |n| dims[n] }
            res = Array.new(out_shape.reduce(1,:*), 0.0)
            strides = ->(sh){ s=Array.new(sh.length,1); (sh.length-2).downto(0){|k| s[k]=s[k+1]*sh[k+1]}; s }
            os = strides.call(out_shape)
            ranges = names.map { |n| (0...dims[n]).to_a }
            ranges.first.product(*ranges[1..]).each do |combo|
              a = {}; names.each_with_index { |n,k| a[n]=combo[k] }
              prod = tensors.reduce(1.0) { |m,(flat,idx,sh)|
                st = strides.call(sh); off = idx.each_with_index.sum { |n,k| a[n]*st[k] }; m*flat[off]
              }
              off = output.each_with_index.sum { |n,k| a[n]*os[k] }
              res[off] += prod
            end
            res
          end
        RUBY
      end
    end
  end
end
