/* vim_bindings.c - simple Vim-like handlers with numeric prefix and dd/yy */
#include <windows.h>
#include <wchar.h>
#include "vim_bindings.h"

static int numeric_prefix = 0; static DWORD last_time = 0; static WORD buf[4]; static int blen = 0;
static void send_vk(WORD vk){ INPUT in[2]; ZeroMemory(in,sizeof(in)); in[0].type=INPUT_KEYBOARD; in[0].ki.wVk=vk; in[1].type=INPUT_KEYBOARD; in[1].ki.wVk=vk; in[1].ki.dwFlags=KEYEVENTF_KEYUP; SendInput(2,in,sizeof(INPUT)); }
static void do_dd(void){ send_vk(VK_HOME); /* shift+end */ INPUT a[2]; ZeroMemory(a,sizeof(a)); a[0].type=INPUT_KEYBOARD; a[0].ki.wVk=VK_SHIFT; a[1].type=INPUT_KEYBOARD; a[1].ki.wVk=VK_END; SendInput(2,a,sizeof(INPUT)); INPUT b[2]; ZeroMemory(b,sizeof(b)); b[0].type=INPUT_KEYBOARD; b[0].ki.wVk=VK_END; b[0].ki.dwFlags=KEYEVENTF_KEYUP; b[1].type=INPUT_KEYBOARD; b[1].ki.wVk=VK_SHIFT; b[1].ki.dwFlags=KEYEVENTF_KEYUP; SendInput(2,b,sizeof(INPUT)); send_vk(VK_DELETE); }
static void do_yy(void){ send_vk(VK_HOME); INPUT a[2]; ZeroMemory(a,sizeof(a)); a[0].type=INPUT_KEYBOARD; a[0].ki.wVk=VK_SHIFT; a[1].type=INPUT_KEYBOARD; a[1].ki.wVk=VK_END; SendInput(2,a,sizeof(INPUT)); INPUT b[2]; ZeroMemory(b,sizeof(b)); b[0].type=INPUT_KEYBOARD; b[0].ki.wVk=VK_END; b[0].ki.dwFlags=KEYEVENTF_KEYUP; b[1].type=INPUT_KEYBOARD; b[1].ki.wVk=VK_SHIFT; b[1].ki.dwFlags=KEYEVENTF_KEYUP; SendInput(2,b,sizeof(INPUT)); /* Ctrl+C */ INPUT c[4]; ZeroMemory(c,sizeof(c)); c[0].type=INPUT_KEYBOARD; c[0].ki.wVk=VK_CONTROL; c[1].type=INPUT_KEYBOARD; c[1].ki.wVk=0x43; c[2].type=INPUT_KEYBOARD; c[2].ki.wVk=0x43; c[2].ki.dwFlags=KEYEVENTF_KEYUP; c[3].type=INPUT_KEYBOARD; c[3].ki.wVk=VK_CONTROL; c[3].ki.dwFlags=KEYEVENTF_KEYUP; SendInput(4,c,sizeof(INPUT)); }

int vim_handle_key(unsigned int vk){ DWORD now = GetTickCount(); if(now - last_time > 800){ blen = 0; numeric_prefix = 0; } last_time = now; if(vk >= 0x30 && vk <= 0x39){ numeric_prefix = numeric_prefix*10 + (vk - 0x30); return 1; } if(blen < 4) buf[blen++] = (WORD)vk; else blen = 0; if(blen >= 2){ if(buf[blen-2]==0x44 && buf[blen-1]==0x44){ int cnt = numeric_prefix?numeric_prefix:1; for(int i=0;i<cnt;i++) do_dd(); numeric_prefix=0; blen=0; return 1; } if(buf[blen-2]==0x59 && buf[blen-1]==0x59){ int cnt = numeric_prefix?numeric_prefix:1; for(int i=0;i<cnt;i++) do_yy(); numeric_prefix=0; blen=0; return 1; } }
    int times = numeric_prefix?numeric_prefix:1; switch(vk){ case 0x48: for(int i=0;i<times;i++) send_vk(VK_LEFT); numeric_prefix=0; blen=0; return 1; case 0x4A: for(int i=0;i<times;i++) send_vk(VK_DOWN); numeric_prefix=0; blen=0; return 1; case 0x4B: for(int i=0;i<times;i++) send_vk(VK_UP); numeric_prefix=0; blen=0; return 1; case 0x4C: for(int i=0;i<times;i++) send_vk(VK_RIGHT); numeric_prefix=0; blen=0; return 1; default: return 0; } }
