; omega.bnf (generated)
<program> ::= { <statement> }
<statement> ::= <decl> ';' | <assign> ';' | <expr> ';' | 'puts' '(' <ident> ')' ';'
<assign> ::= <lhs> ( '=>' | '>-') <rhs>
<lhs> ::= <ident> | <expr>
<rhs> ::= <ident> | <expr> | <object-literal>
<decl> ::= 'array' <ident> '=' '[' <string-list> ']'
<decl> ::= 'list' <ident> '=' 'list' '(' <string-list> ')'
<decl> ::= 'hash' <ident> '=' '{' <hash-pairs> '}'
<decl> ::= 'func' <ident> '=' 'func' '(' <number> ')'
<expr> ::= <ident> | <call> | <string> | <number>
<call> ::= <ident> '(' [ <args> ] ')'
<string-list> ::= <string> { ',' <string> }
<hash-pairs> ::= <string> ':' <number> { ',' <string> ':' <number> }
<ident> ::= /[A-Za-z_][A-Za-z0-9_:]*/
<string> ::= /\"(?:[^\"\\]|\\.)*\"/
<number> ::= /[0-9]+/
