了解しました。数式の多様性（構文バリエーション・合成パターン・確率的生成・LaTeX整形）を高めるため、先に作成したパッケージ内の `tools/theory_gen.py` を差し替える内容を示します。これを保存して実行すると、多様な構造の数式（演算子合成、和積分、微分作用素、テンソル、特殊関数、ランダム係数など）を生成します。

手順（簡潔）
1. omega_theory_pkg/tools/theory_gen.py を以下の内容に置き換える（上書き保存）。
2. 実行例:
   - python3 omega_theory_pkg/tools/theory_gen.py --count 10 --outdir omega_theory_pkg/generated --seed 1234

   置換用スクリプト全文（保存先: omega_theory_pkg/tools/theory_gen.py）
```python
#!/usr/bin/env python3
# theory_gen.py - enhanced formula diversity generator
# Usage: python3 theory_gen.py --count N --outdir path --seed S

   import os, sys, argparse, random, datetime, math

LATEX_SPECIAL = [
		 r"\alpha", r"\beta", r"\gamma", r"\delta", r"\epsilon", r"\zeta", r"\eta",
		 r"\theta", r"\kappa", r"\lambda", r"\mu", r"\nu", r"\xi", r"\pi", r"\rho",
		 r"\sigma", r"\tau", r"\phi", r"\chi", r"\psi", r"\omega"
]

OPERATORS = [
	     r"+", r"-", r"\cdot", r"\times", r"\wedge", r"\otimes", r"\circ"
]

FUNCTIONS = [
	     r"\sin", r"\cos", r"\exp", r"\log", r"\Gamma", r"\zeta", r"\mathrm{erf}",
	     r"\mathrm{Li}_2", r"\mathrm{Ai}"
]

TEMPLATE_PATTERNS = [
    # spectral / series style
		     r"\sum_{n=1}^{\infty} a_{n} %s %s",
    # integral geometry
		     r"\int_{M} (%s) \, dV = %s",
    # PDE style
		     r"\partial_{t} %s = %s + %s",
    # tensor relation
		     r"%s_{\\mu\\nu} = %s \\; + \\; \\nabla_{\\mu}\\nabla_{\\nu} %s",
    # functional equation
		     r"F(s) = %s(s) + \\int_{0}^{\\infty} K(s,t) G(t) \\, dt",
    # operator composition
		     r"\\mathcal{O} = %s \\circ %s + \\sum_{k=0}^{N} c_k %s^{k}",
    # mixed analytic-spectral
		     r"x^{%s + i %s} = \\exp\\big(%s \\log x\\big) + \\varepsilon(x)",
]

FRAGMENTS = [
	     r"e^{\\lambda_n x}", r"\\frac{1}{(n+\\alpha)^s}", r"\\nabla_{i}\\nabla_{j} f",
	     r"|\\nabla f|^{2}", r"R + |\\nabla f|^{2}", r"\\Delta f", r"\\mathrm{tr}\\,T",
	     r"\\frac{d^{2}}{dx^{2}}", r"\\int_{0}^{1} t^{\\beta-1}(1-t)^{\\gamma-1} dt"
]

	     RNG = random.Random()

	     def pick(pool):
	     return RNG.choice(pool)

	     def rand_coeff():
    # small integer or rational-like string
	     if RNG.random() < 0.2:
	     return str(RNG.randint(-5,5))
	     num = RNG.randint(1,9)
	     den = RNG.randint(1,9)
	       return r"\frac{%d}{%d}" % (num, den)

	       def symbol():
	       return pick(LATEX_SPECIAL)

		 def op():
		 return pick(OPERATORS)

		   def func(name=None, arg=None):
		   if name is None: name = pick(FUNCTIONS)
		     if arg is None: arg = pick([r"x", r"t", r"s", r"y", r"z"])
    return name + "(" + arg + ")"

		       def fragment():
    # Compose fragment probabilistically
		       p = RNG.random()
		       if p < 0.25:
		     return rand_coeff() + r" " + op() + " " + pick(FRAGMENTS)
		       if p < 0.5:
		       return func() + " " + op() + " " + pick(FRAGMENTS)
			 if p < 0.75:
			 return pick(FRAGMENTS) + r" \; + \; " + func()
			   return r"\langle %s, %s \\rangle" % (symbol(), pick(FRAGMENTS))

			   def synth_formula():
    # choose template and fill with varied fragments
			   templ = pick(TEMPLATE_PATTERNS)
    parts = []
    # count placeholders in template roughly by number of %s
			     needed = templ.count("%s")
			     for _ in range(needed):
        # sometimes build composite fragment
			     if RNG.random() < 0.4:
			       parts.append(fragment())
			       else:
				 parts.append(func() if RNG.random() < 0.5 else pick(FRAGMENTS))
    # occasionally add random operator chain
				   if RNG.random() < 0.3:
				   chain = " ".join([rand_coeff(), op(), symbol()])
				     parts.append(chain)
    # substitute
				     try:
				     filled = templ % tuple(parts[:needed])
				       except Exception:
        # fallback safe join
				   filled = templ.replace("%s", "{}").format(*parts[:needed])
    # sometimes wrap with additional equality or limit statements
    tail = ""
				   if RNG.random() < 0.25:
        tail = r",\quad\text{as } x\to\infty"
	  if RNG.random() < 0.2:
        tail = r",\quad \lim_{n\to\infty} a_n = 0"
    return filled + tail

	  def make_text(title, formula):
	  hdr = "# Generated Theory: %s\n# %s\n\n" % (title, datetime.datetime.utcnow().isoformat())
    body = "Abstract:\nAutogenerated diverse formulaic fragment for exploration.\n\n"
    body += "Conjecture:\n" + r"\begin{equation}" + "\n" + formula + "\n" + r"\end{equation}" + "\n\n"
	    body += "Notes:\n- Symbols: %s\n- Coeffs random: %s\n\n" % (", ".join(RNG.sample(LATEX_SPECIAL, k=min(4,len(LATEX_SPECIAL)))), rand_coeff())
    body += "Disclaimer: synthetic output — requires rigorous verification.\n"
    return hdr + body

	    def main():
	    p = argparse.ArgumentParser()
	      p.add_argument('--count', type=int, default=1)
	      p.add_argument('--outdir', default='generated')
	      p.add_argument('--seed', type=int, default=None)
	      args = p.parse_args()
	      if args.seed is not None:
	      RNG.seed(args.seed)
	      os.makedirs(args.outdir, exist_ok=True)
	      for i in range(args.count):
	      title = 'omega_theory_%03d' % (i+1)
		formula = synth_formula()
		text = make_text(title, formula)
		fname_txt = os.path.join(args.outdir, title + '.md')
		fname_tex = os.path.join(args.outdir, title + '.tex')
		with open(fname_txt, 'w', encoding='utf-8') as f:
		f.write(text)
		with open(fname_tex, 'w', encoding='utf-8') as f:
		f.write('% Auto LaTeX for %s\n\\begin{equation}\\label{eq:%s}\n' % (title, title))
		f.write(formula + "\n")
		f.write("\\end{equation}\n")
		print('Wrote', args.count, 'theory files to', args.outdir)

	      if __name__ == '__main__':
	      main()
```

簡単なカスタマイズ案（必要なら実装します）
- テンプレート・断片を増やす（特殊関数、群論式、確率微分方程式など）。
- 係数分布をガウスや有理数に変更。
- 構文木（AST）生成で文法的に一貫した式を作る（より高度）。
- 外部モデルを使った自然言語→数式合成（要API鍵・注意）。

ご希望なら（1）さらに多様なテンプレート追加、（2）ASTベース生成スニペット、（3）自動LaTeX検査（コンパイル） のいずれかを実装します。どれを優先しますか？
