package.lib
/*
static const char *lib_zeta_utils =
# zeta_utils.py\n"
# Minimal zeta/gamma utilities using sympy and mpmath fallback.\n"
from sympy import symbols, zeta as sym_zeta, gamma as sym_gamma, I as symI, N as symN\n"
import mpmath as mp\n"
import re\n\n"
def parse_complex(s):\n"
    s = s.strip().replace(' ', '')\n"
    if s.endswith('i'):\n"
        s2 = s[:-1]\n"
        m = re.match(r'^([+-]?\\d*\\.?\\d+)([+-]\\d*\\.?\\d+)$', s2)\n"
        if m:\n"
            return complex(float(m.group(1)), float(m.group(2)))\n"
        return complex(0.0, float(s2))\n"
    else:\n"
        return complex(float(s), 0.0)\n\n"
def zeta_value(s):\n"
    try:\n"
        from sympy import I as symI\n"
        if isinstance(s, complex):\n"
            sx = s.real + s.imag*symI\n"
            return complex(symN(sym_zeta(sx), 50))\n"
        else:\n"
            return sym_zeta(s)\n"
    except Exception:\n"
        mp.mp.dps = 50\n"
        return mp.zeta(s)\n\n"
def gamma_value(s):\n"
    try:\n"
        from sympy import I as symI\n"
        if isinstance(s, complex):\n"
            sx = s.real + s.imag*symI\n"
            return complex(symN(sym_gamma(sx),50))\n"
        else:\n"
            return sym_gamma(s)\n"
    except Exception:\n"
        mp.mp.dps = 50\n"
        return mp.gamma(s)\n\n"
def functional_equation_xi(s):\n"
    try:\n"
        from sympy import I as symI, pi\n"
        if isinstance(s, complex):\n"
            sx = s.real + s.imag*symI\n"
            xi = sym_gamma(sx/2)*(pi**(-sx/2))*sym_zeta(sx)\n"
            sm = 1 - sx\n"
            xi_m = sym_gamma(sm/2)*(pi**(-sm/2))*sym_zeta(sm)\n"
            return (complex(symN(xi,40)), complex(symN(xi_m,40)))\n"
        else:\n"
            xi = sym_gamma(s/2)*(pi**(-s/2))*sym_zeta(s)\n"
            sm = 1 - s\n"
            xi_m = sym_gamma(sm/2)*(pi**(-sm/2))*sym_zeta(sm)\n"
            return (xi, xi_m)\n"
    except Exception:\n"
        mp.mp.dps = 50\n"
        if isinstance(s, complex):\n"
            xi = mp.gamma(s/2)*(mp.pi**(-s/2))*mp.zeta(s)\n"
            sm = 1 - s\n"
            xi_m = mp.gamma(sm/2)*(mp.pi**(-sm/2))*mp.zeta(sm)\n"
            return (xi, xi_m)\n"
        return (None, None)\n";
*/


