package forge.bada.app

import android.app.Activity
import android.os.Bundle
import android.webkit.WebView
import android.webkit.WebSettings

/**
 * Bada Forge — a WebView host for the Bada Forge source auto-correction IDE.
 *
 * The IDE (assets/index.html) is generated by the Bada program
 * apps/bada_forge.bada and runs the integrable-system / spinning-top error
 * correction engine entirely in the WebView (JavaScript port of lib/forge.bada).
 */
class MainActivity : Activity() {
    private lateinit var web: WebView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        web = WebView(this)
        val s: WebSettings = web.settings
        s.javaScriptEnabled = true
        s.domStorageEnabled = true
        s.builtInZoomControls = true
        s.displayZoomControls = false
        web.loadUrl("file:///android_asset/index.html")
        setContentView(web)
    }

    override fun onBackPressed() {
        if (web.canGoBack()) web.goBack() else super.onBackPressed()
    }
}
