"""
emacskeys.runner
Usage: python3 -m emacskeys.runner --config-file mymap.json
Reads a JSON config describing hotkey -> send mappings, generates an AutoHotkey script,
and registers it to run at login (HKCU Run). Requires Windows + Python + AutoHotkey.
"""
import os
import sys
import json
import argparse

def find_ahk_exe():
    candidates = [
        r"C:\\Program Files\\AutoHotkey\\AutoHotkey.exe",
        r"C:\\Program Files (x86)\\AutoHotkey\\AutoHotkey.exe",
        r"C:\\Program Files\\AutoHotkey\\AutoHotkey64.exe",
    ]
    for p in candidates:
        if os.path.exists(p):
            return p
    return None

def key_to_ahk(hk):
    # simple translation: expect JSON keys like "C-a", "M-x", "h", "j" etc.
    # C- -> Ctrl, M- -> Alt, S- -> Shift
    parts = hk.split('-') if '-' in hk else [hk]
    mods = ''
    key = ''
    if len(parts) == 1:
        key = parts[0]
    else:
        for p in parts[:-1]:
            if p.upper() == 'C': mods += '^'
            elif p.upper() == 'M': mods += '!'
            elif p.upper() == 'S': mods += '+'
        key = parts[-1]
    # convert single letters to AHK literal (case-insensitive)
    if len(key) == 1 and key.isalpha():
        return mods + key.lower()
    # common names
    mapping = {'esc':'Esc', 'enter':'Enter', 'tab':'Tab', 'space':'Space', 'left':'Left', 'right':'Right', 'up':'Up', 'down':'Down'}
    lk = key.lower()
    if lk in mapping:
        return mods + mapping[lk]
    # fallback: raw
    return mods + key

def generate_ahk(mapdict, outpath):
    lines = []
    lines.append("; Auto-generated by emacskeys.runner")
    for hk, action in mapdict.items():
        ahkkey = key_to_ahk(hk)
        # action supports simple send string or mapping to other key like "Left"
        if isinstance(action, str):
            send = action.replace('\\\\', '\\\\')
            # escape { in AHK by sending raw text via SendRaw if needed
            if any(c in send for c in '{}'):
                lines.append(f"{ahkkey}::SendRaw {send}")
            else:
                lines.append(f"{ahkkey}::Send {send}")
        else:
            # unsupported type -> ignore
            continue
    with open(outpath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

def register_run(exe, script_path, name='emacskeys_ahk'):
    try:
        import winreg
    except Exception as e:
        print('Registering to Run key requires Windows Python (winreg).', file=sys.stderr)
        return False
    runkey = r"Software\\Microsoft\\Windows\\CurrentVersion\\Run"
    cmd = f'"{exe}" "{script_path}"'
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, runkey, 0, winreg.KEY_SET_VALUE) as k:
            winreg.SetValueEx(k, name, 0, winreg.REG_SZ, cmd)
        return True
    except Exception as e:
        print('Failed to write Run registry key:', e, file=sys.stderr)
        return False

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--config-file', required=True, help='Path to mymap.json')
    parser.add_argument('--no-register', action='store_true', help='Do not write Run registry entry')
    args = parser.parse_args()
    cfg = args.config_file
    if not os.path.exists(cfg):
        print('Config not found:', cfg, file=sys.stderr); sys.exit(2)
    with open(cfg, 'r', encoding='utf-8') as f:
        try:
            j = json.load(f)
        except Exception as e:
            print('Failed to parse JSON:', e, file=sys.stderr); sys.exit(3)
    # expect format: { "bindings": { "C-a": "Home", "C-e": "End", "h": "Left" } }
    bindings = j.get('bindings') if isinstance(j, dict) else None
    if not bindings:
        print('No bindings found in JSON. Expected top-level "bindings" object.', file=sys.stderr); sys.exit(4)

    # create output dir inside package location
    base = os.path.dirname(__file__)
    outdir = os.path.join(base, 'generated')
    os.makedirs(outdir, exist_ok=True)
    ahk_path = os.path.join(outdir, 'emacskeys_remap.ahk')
    generate_ahk(bindings, ahk_path)
    print('Generated AHK script at', ahk_path)

    ahkexe = find_ahk_exe()
    if not ahkexe:
        print('AutoHotkey executable not found in common locations. You must install AutoHotkey and either move it to a standard location or register manually.', file=sys.stderr)
        print('AHK script can be run manually:', ahk_path)
        sys.exit(0)

    if args.no_register:
        print('Skipping registry registration (--no-register). To run now:')
        print(f'"{ahkexe}" "{ahk_path}"')
        sys.exit(0)

    ok = register_run(ahkexe, ahk_path)
    if ok:
        print('Registered AHK script to startup (HKCU Run). It will run on next login. You can run it now:')
        print(f'"{ahkexe}" "{ahk_path}"')
        sys.exit(0)
    else:
        sys.exit(1)

if __name__ == '__main__':
    main()
